"""Synthesis prompt v1 — the text is docs/11-prompts.md verbatim.

Do not edit this file to improve output. Add v2. The version number is recorded against every
import, and rewriting v1 in place makes those records lie.
"""

from typing import Any

from receptenapp.services.evidence import EvidenceBundle

MAX_OUTPUT_TOKENS = 5000
"""A backstop against runaway generation, not a budget.

docs/11 targets a *mean* under 900 output tokens, and a blog recipe lands near that. The ceiling has
to clear the worst honest case by a wide margin, because hitting it fails an import that was going
fine. 2400 looked generous and was not: a 34-segment TikTok transcript blew straight through it —
the schema spends 13 keys per ingredient, so verbose recipes cost far more output than the prose
suggests. At mini rates 5000 tokens is well under a cent.

Not part of the prompt's semantics, so changing it does not need a new version: it cannot change
what a successful call returns.
"""

SYSTEM_PROMPT = """\
You extract recipes from source material and return structured data. You are careful,
literal, and you never invent information.

## Output language

All user-visible strings — title, description, ingredient names, qualifiers, step text —
must be Dutch. Informal register: "je", never "u". Warm and plain, the way a friend
writes down a recipe. No marketing language, no "heerlijke romige".

Translate ingredient names to the term a Dutch home cook uses:
  scallion / green onion -> lente-ui
  cilantro -> koriander
  heavy cream -> slagroom
  all-purpose flour -> bloem
  baking soda -> baking soda        (NOT zuiveringszout)
  cornstarch -> maizena
  eggplant -> aubergine
  zucchini -> courgette
  bell pepper -> paprika
  ground beef -> rundergehakt
  shrimp -> garnalen
  broth / stock -> bouillon

## Units

`unit` must be one of exactly:
  g, kg, ml, l, el, tl, stuk, snuf, teentje, bosje, blikje, pakje, plak, handvol, naar_smaak

Never invent a unit. If nothing fits, use null and put the measure in `qualifier`.

Use `naar_smaak` with amount null for unquantified seasoning ("peper en zout naar smaak").
Do not fabricate a number for these.

## Conversions

Convert all imperial and US measures to metric. Volume-to-weight is INGREDIENT DEPENDENT.
There is no formula. Use these:

  1 cup bloem            = 125 g
  1 cup suiker           = 200 g
  1 cup basterdsuiker    = 220 g (packed)
  1 cup poedersuiker     = 120 g
  1 cup boter            = 225 g
  1 cup rijst (ongekookt)= 185 g
  1 cup havermout        = 90 g
  1 cup geraspte kaas    = 100 g
  1 cup gehakte noten    = 120 g
  1 cup cacaopoeder      = 100 g
  1 cup water/melk       = 240 ml

  1 US cup     = 237 ml       1 metric cup = 250 ml
  1 stick butter = 113 g      1 lb = 454 g       1 oz = 28 g
  1 US tbsp = 15 ml           1 US tsp = 5 ml
  1 AU tbsp = 20 ml           (Australian sources only)

Temperature: °F -> °C, round to nearest 5.
British gas mark: 1=140, 2=150, 3=170, 4=180, 5=190, 6=200, 7=220, 8=230, 9=240 °C.
Do NOT compute a fan-oven variant. The application does that.

When you convert, preserve the original in `orig_amount` and `orig_unit`, and set
`prov` to "derived". A converted value is NEVER "explicit".

## Amounts and rounding

Round to amounts a person can measure. 236.6 ml -> 240 ml. 113.4 g -> 115 g.
For countable items that don't divide cleanly, use `amount` + `amount_max`:
  1.33 eggs -> amount 1, amount_max 2
Never output a fractional egg, onion, or clove.

## Method steps

REWRITE every step in your own words. Do not copy the source's sentences, even
partially. This is a legal requirement, not a style preference. Keep the cooking
information identical; discard the storytelling, the anecdotes, and the padding.

One action per step where possible. Imperative mood: "Verhit de olie in een pan."
Maximum ~2 sentences per step.

Set `timer_seconds` when a step contains a duration ("laat 20 minuten sudderen" ->
1200). Set `temperature_c` when a step names an oven temperature.
Set `ingredient_pos` to the positions of ingredients used in that step.

## Provenance — the most important rule in this prompt

Every field carries a provenance value. Be strict and honest:

  explicit  — the value was literally stated or written in the source material.
              You can point at the words.
  derived   — you computed it from something explicit: a unit conversion, a total
              time summed from steps, servings inferred from "serves a family of four".
  estimated — you supplied it from general cooking knowledge. The source does not
              support it.
  missing   — not determinable. Use null for the value.

A converted quantity is "derived", never "explicit".
A translated ingredient name is still "explicit" — translation does not change
what the source said.
If you are unsure whether something was stated, it was not. Use "derived" or
"missing".

## Never invent

Do NOT guess: servings, oven temperature, prep time, cook time, difficulty.
If the source does not support them, set the value to null, set provenance to
"missing", and add the field name to `missing`.

An empty field the user fills in is good. A plausible wrong number is a bug that
destroys trust, because the user has no way to know it was invented.

You MAY infer `meal_types` and `category` from general knowledge — those are
classifications, not facts about the recipe. Mark inferred `meal_types` as derived.

## Not a recipe

If the source contains no recipe — it is a restaurant review, a haul video, a
grocery run, an ad — set `found` to false, `confidence` to "low", and return empty
arrays. Do not construct a recipe from a food-adjacent post.

## Confidence

  high   — ingredients and steps both complete and unambiguous
  medium — usable, but some quantities or steps are thin
  low    — fragmentary; the user will have to do real work

## Evidence quality

You will receive some of: structured recipe data, a page text extract, a video
transcript, a post caption. Trust them in that order.

Transcripts are speech: they contain false starts, "een beetje", "zo'n", and
approximations. Convert vague speech to concrete amounts ONLY when the speaker gives
one. "Een flinke scheut olijfolie" is not 3 tablespoons — it is `naar_smaak` with
qualifier "flinke scheut", or 1 el marked "estimated" if a number is genuinely needed.

## Worked example

Input fragment (TikTok transcript):

  okay so for this you need two cups of flour, a stick of butter, and I usually
  just eyeball the salt. mix it all up, bake it until golden, done.

Correct output (abbreviated):

{
  "found": true,
  "confidence": "low",
  "title": "Simpele boterkoekjes",
  "servings": null,
  "oven_c": null,
  "cook_minutes": null,
  "ingredients": [
    { "pos": 1, "amount": 250, "unit": "g", "name_nl": "bloem",
      "category": "houdbaar", "raw": "two cups of flour",
      "orig_amount": 2, "orig_unit": "cups", "prov": "derived", "optional": false },
    { "pos": 2, "amount": 113, "unit": "g", "name_nl": "boter",
      "category": "zuivel_eieren", "raw": "a stick of butter",
      "orig_amount": 1, "orig_unit": "stick", "prov": "derived", "optional": false },
    { "pos": 3, "amount": null, "unit": "naar_smaak", "name_nl": "zout",
      "category": "kruiden_specerijen", "raw": "eyeball the salt",
      "prov": "explicit", "optional": false }
  ],
  "steps": [
    { "pos": 1, "text": "Meng de bloem, boter en het zout tot een samenhangend deeg.",
      "ingredient_pos": [1, 2, 3], "prov": "explicit" },
    { "pos": 2, "text": "Bak de koekjes tot ze goudbruin zijn.",
      "prov": "explicit" }
  ],
  "field_provenance": {
    "title": "derived", "servings": "missing", "prep_minutes": "missing",
    "cook_minutes": "missing", "oven_c": "missing", "difficulty": "derived"
  },
  "missing": ["servings", "oven_c", "cook_minutes"]
}
"""

_UNITS = [
    "g",
    "kg",
    "ml",
    "l",
    "el",
    "tl",
    "stuk",
    "snuf",
    "teentje",
    "bosje",
    "blikje",
    "pakje",
    "plak",
    "handvol",
    "naar_smaak",
]

_CATEGORIES = [
    "groente_fruit",
    "vlees_vis",
    "zuivel_eieren",
    "brood_bakkerij",
    "houdbaar",
    "kruiden_specerijen",
    "diepvries",
    "dranken",
    "overig",
]

_PROVENANCE = ["explicit", "derived", "estimated", "missing"]


def _nullable(*types: str) -> list[str]:
    return [*types, "null"]


# OpenAI strict structured outputs require every key in `properties` to appear in `required` and
# `additionalProperties: false` at every level. Optionality is expressed by allowing null, not by
# omitting the key. Numeric bounds and string lengths are deliberately absent — see
# schemas/synthesis.py for where they are enforced instead.
JSON_SCHEMA: dict[str, Any] = {
    "type": "object",
    "additionalProperties": False,
    "required": [
        "found",
        "confidence",
        "title",
        "description",
        "meal_types",
        "servings",
        "prep_minutes",
        "cook_minutes",
        "difficulty",
        "oven_c",
        "ingredients",
        "steps",
        "field_provenance",
        "missing",
    ],
    "properties": {
        "found": {
            "type": "boolean",
            "description": "false if the source contains no recipe at all",
        },
        "confidence": {"type": "string", "enum": ["high", "medium", "low"]},
        "title": {"type": "string"},
        "description": {"type": _nullable("string")},
        "meal_types": {
            "type": "array",
            "items": {
                "type": "string",
                "enum": ["ontbijt", "lunch", "diner", "tussendoor"],
            },
        },
        "servings": {"type": _nullable("integer")},
        "prep_minutes": {"type": _nullable("integer")},
        "cook_minutes": {"type": _nullable("integer")},
        "difficulty": {
            "type": _nullable("string"),
            "enum": ["makkelijk", "gemiddeld", "uitdagend", None],
        },
        "oven_c": {"type": _nullable("integer")},
        "ingredients": {
            "type": "array",
            "items": {
                "type": "object",
                "additionalProperties": False,
                "required": [
                    "pos",
                    "section",
                    "amount",
                    "amount_max",
                    "unit",
                    "name_nl",
                    "qualifier",
                    "category",
                    "optional",
                    "raw",
                    "orig_amount",
                    "orig_unit",
                    "prov",
                ],
                "properties": {
                    "pos": {"type": "integer"},
                    "section": {"type": _nullable("string")},
                    "amount": {"type": _nullable("number")},
                    "amount_max": {"type": _nullable("number")},
                    "unit": {"type": _nullable("string"), "enum": [*_UNITS, None]},
                    "name_nl": {"type": "string"},
                    "qualifier": {"type": _nullable("string")},
                    "category": {"type": "string", "enum": _CATEGORIES},
                    "optional": {"type": "boolean"},
                    "raw": {"type": "string"},
                    "orig_amount": {"type": _nullable("number")},
                    "orig_unit": {"type": _nullable("string")},
                    "prov": {"type": "string", "enum": _PROVENANCE},
                },
            },
        },
        "steps": {
            "type": "array",
            "items": {
                "type": "object",
                "additionalProperties": False,
                "required": [
                    "pos",
                    "text",
                    "timer_seconds",
                    "temperature_c",
                    "ingredient_pos",
                    "prov",
                ],
                "properties": {
                    "pos": {"type": "integer"},
                    "text": {"type": "string"},
                    "timer_seconds": {"type": _nullable("integer")},
                    "temperature_c": {"type": _nullable("integer")},
                    "ingredient_pos": {"type": "array", "items": {"type": "integer"}},
                    "prov": {"type": "string", "enum": _PROVENANCE},
                },
            },
        },
        "field_provenance": {
            "type": "object",
            "additionalProperties": False,
            "required": [
                "title",
                "servings",
                "prep_minutes",
                "cook_minutes",
                "oven_c",
                "difficulty",
            ],
            "properties": {
                "title": {"type": "string", "enum": _PROVENANCE},
                "servings": {"type": "string", "enum": _PROVENANCE},
                "prep_minutes": {"type": "string", "enum": _PROVENANCE},
                "cook_minutes": {"type": "string", "enum": _PROVENANCE},
                "oven_c": {"type": "string", "enum": _PROVENANCE},
                "difficulty": {"type": "string", "enum": _PROVENANCE},
            },
        },
        "missing": {
            "type": "array",
            "items": {"type": "string"},
            "description": "field names the user should supply, for the amber card",
        },
    },
}


def build_user_message(bundle: EvidenceBundle) -> str:
    """Label each kind of evidence separately.

    The labels are load-bearing, not decoration: the prompt tells the model to trust structured
    data over page text over transcript over caption, and merging them into one blob throws away
    the only thing that distinguishes them.
    """
    lines = [f"Source: {bundle.platform}"]
    if bundle.author:
        lines.append(f"Author: {bundle.author}")
    if bundle.title and bundle.title != bundle.caption:
        lines.append(f"Title: {bundle.title}")
    lines.append("")

    if bundle.structured:
        lines += ["--- STRUCTURED RECIPE DATA (schema.org) ---", str(bundle.structured), ""]
    if bundle.page_text:
        lines += ["--- PAGE TEXT ---", bundle.page_text, ""]
    if transcript := bundle.transcript_text:
        lines += ["--- TRANSCRIPT ---", transcript, ""]
    if bundle.caption:
        lines += ["--- CAPTION ---", bundle.caption, ""]

    lines.append("Extract the recipe as structured data.")
    return "\n".join(lines)
